import QRCode from 'qrcode';
import './styles.css';
import {books,dashboard} from './data/demo.js';
import {track,campaignUrl} from './lib/analytics.js';

const app=document.querySelector('#app');
const state={view:'store',filter:'All',query:'',cart:JSON.parse(localStorage.getItem('yr.market.cart')||'[]'),selected:null};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const liveEditions=b=>b.editions.filter(e=>e.status==='live');
const minPrice=b=>Math.min(...liveEditions(b).map(e=>e.price));
const brandMark=`<span class="brandMark"><svg viewBox="0 0 64 64" aria-hidden="true"><path d="M12 10h12l8 15 8-15h12L37 36v17H27V36z" fill="white"/><circle cx="50" cy="49" r="5.5" fill="#C6FF00"/></svg></span>`;

function persistCart(){localStorage.setItem('yr.market.cart',JSON.stringify(state.cart));}
function shell(){return `<div class="navWrap"><div class="shell nav"><button class="brand" data-nav="store">${brandMark}<span class="brandName">Marketplace <span class="brandDot">|</span> YasReady<small>Books. Direct.</small></span></button><div class="navlinks"><button data-nav="store" class="${state.view==='store'?'active':''}">Marketplace</button><button data-nav="dashboard" class="${state.view==='dashboard'?'active':''}">Author Dashboard</button><button data-nav="marketing" class="${state.view==='marketing'?'active':''}">Marketing Kit</button></div><div class="navright"><button class="iconButton cartBtn" data-cart>Cart<span class="cartCount ${state.cart.length?'':'hidden'}">${state.cart.length}</span></button><button class="avatar" data-nav="dashboard">W</button></div></div></div><div class="modeStrip"><div class="shell"><p><strong>Marketplace Foundation v0.1.0</strong> · Demo data is local. Live checkout and fulfillment are fail-closed until credentials + certification are added.</p><span class="safePill">SAFE DEMO MODE</span></div></div>`}

function cover(b,small=false){return `<div class="cover ${small?'small':''}" style="background:${b.cover}"><h3>${b.title}</h3><p>${b.subtitle||b.author}</p></div>`}
function bookCard(b){return `<article class="bookCard">${cover(b)}<div class="bookMeta"><h3>${b.title}</h3><p>${b.author}${b.seriesNumber?` · Book ${b.seriesNumber}`:''}</p><div class="rating">★ ${b.rating} · ${b.reviews} reviews</div><div class="editionChips">${b.editions.map(e=>`<span class="editionChip ${e.status==='live'?'live':''}">${e.format}${e.status!=='live'?` · ${e.status}`:''}</span>`).join('')}</div><div class="cardBottom"><div class="from">From<strong>${money(minPrice(b))}</strong></div><button class="btn secondary small" data-book="${b.id}">View book</button></div></div></article>`}
function storeView(){
  const filtered=books.filter(b=>{const q=state.query.toLowerCase();const matches=!q||`${b.title} ${b.author} ${b.categories.join(' ')}`.toLowerCase().includes(q);const fmt=state.filter==='All'||b.editions.some(e=>e.format===state.filter&&e.status==='live');return matches&&fmt});
  return `<main class="view"><section class="hero"><div class="shell heroGrid"><div><span class="kicker">Books made sellable</span><h1>The last step shouldn't be <span>“good luck.”</span></h1><p>Marketplace | YasReady turns finished books into storefronts, sales data, author earnings and marketing tools — without making authors rebuild everything they already entered while publishing.</p><div class="heroActions"><button class="btn primary" data-scroll="browse">Browse books</button><button class="btn secondary" data-nav="dashboard">See the author side</button></div><div class="trustRow"><span>Multi-format listings</span><span>Attribution built in</span><span>Ingram-ready fulfillment</span><span>Stripe-ready payouts</span></div></div><aside class="heroPanel"><span class="kicker">From Publishing to Marketplace</span><h3>Your book is ready. Now sell it.</h3><p>The commercial record stays with the book: editions, pricing, orders, campaigns, fulfillment and author earnings.</p><div class="heroBook"><div class="miniCover" style="background:${books[1].cover}"></div><div><strong>${books[1].title}</strong><small>${books[1].author}</small><div class="formatDots"><span><i class="liveDot"></i>Paperback live</span><span>Ebook live</span><span>Audio next</span></div></div></div></aside></div></section>
  <section class="section" id="browse"><div class="shell"><div class="sectionHead"><div><span class="kicker">Marketplace</span><h2>One title. Every format.</h2></div><p>A consumer-first bookstore on the outside, a structured commerce engine for authors underneath.</p></div><div class="searchRow"><div class="searchBox"><span class="searchIcon">⌕</span><input id="search" placeholder="Search title, author or category" value="${state.query.replaceAll('"','&quot;')}"></div><div class="filters">${['All','Ebook','Paperback','Hardcover','Audiobook'].map(f=>`<button class="filterBtn ${state.filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div></div><div class="bookGrid">${filtered.map(bookCard).join('')||'<div class="empty">No books match that search.</div>'}</div></div></section>
  <section class="section"><div class="shell flowBand"><div><span class="kicker">The YasReady loop</span><h2>Make it. Sell it. Understand it.</h2><p>Publishing makes the book. Marketplace sells it and captures clean commercial data. Business can eventually consume those numbers without asking the author to re-enter them.</p></div><div class="flowSteps"><div class="flowStep"><div class="flowNum">1</div><div><strong>Publishing | YasReady</strong><small>Creates the finished title and its editions. No Marketplace code needs to live inside Publishing.</small></div></div><div class="flowStep"><div class="flowNum">2</div><div><strong>Marketplace | YasReady</strong><small>Owns listings, checkout, fulfillment state, marketing attribution, customer orders and author earnings.</small></div></div><div class="flowStep"><div class="flowNum">3</div><div><strong>Business | YasReady</strong><small>Later consumes normalized revenue and channel data as one more source in the Business Brain.</small></div></div></div></div></section></main>`
}
function lineChart(vals){const w=700,h=190,p=12,max=Math.max(...vals),min=Math.min(...vals);const pts=vals.map((v,i)=>`${p+i*(w-2*p)/(vals.length-1)},${h-p-(v-min)/(max-min||1)*(h-2*p)}`).join(' ');const area=`${p},${h-p} ${pts} ${w-p},${h-p}`;return `<svg class="chartSvg" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><g class="chartGrid"><line x1="0" y1="48" x2="700" y2="48"/><line x1="0" y1="95" x2="700" y2="95"/><line x1="0" y1="142" x2="700" y2="142"/></g><polygon class="chartArea" points="${area}"/><polyline class="chartLine" points="${pts}"/></svg>`}
function dashboardView(){return `<main class="view dashboard"><div class="shell"><div class="dashHero"><div><span class="kicker">Author commerce</span><h1>Your books are a business.</h1><p>Demo: William · ${dashboard.period} · Marketplace data model already separates gross sales, seller earnings, fees, refunds, formats and attribution.</p></div><div class="dashActions"><button class="btn secondary" data-nav="marketing">Open Marketing Kit</button><button class="btn primary" data-toast="Business export is modeled but intentionally disconnected in v0.1.0.">Connect to Business</button></div></div><div class="metricGrid"><div class="metric"><span>Gross marketplace sales</span><strong>${money(dashboard.grossSales)}</strong><small>Before fulfillment, fees and refunds</small></div><div class="metric"><span>Author earnings</span><strong>${money(dashboard.authorEarnings)}</strong><small>Accrued seller proceeds</small></div><div class="metric"><span>Units sold</span><strong>${dashboard.units}</strong><small>Across all formats</small></div><div class="metric"><span>Conversion rate</span><strong>${dashboard.conversionRate}%</strong><small>Tracked visits → purchases</small></div></div>
  <div class="dashGrid"><section class="panel"><span class="kicker">Sales pulse</span><h3>Revenue is becoming a dataset.</h3><p>Marketplace events are designed to land as immutable analytics records so future reporting does not depend on reconstructing activity from orders later.</p><div class="chartWrap">${lineChart(dashboard.daily)}</div></section><section class="panel dark"><span class="kicker">Format mix</span><h3>What readers are buying</h3><p>Edition-level reporting is native, including audiobook from day one.</p><div class="mixRows">${dashboard.formatMix.map(x=>`<div class="mixRow"><span>${x.label}</span><div class="mixBar"><i style="width:${x.value}%"></i></div><strong>${x.value}%</strong></div>`).join('')}</div></section></div>
  <div class="dashGrid"><section class="panel"><span class="kicker">Attribution</span><h3>Know what actually sells books.</h3><p>Every YasReady link, QR and embed can carry campaign identifiers into the same event ledger.</p><div class="sourceRows">${dashboard.sources.map(s=>`<div class="sourceRow"><div><strong>${s.source}</strong><small>${s.visits} visits</small></div><span>${s.sales} sales</span><span>${money(s.revenue)}</span><span>${s.conversion}% CVR</span></div>`).join('')}</div></section><section class="panel"><span class="kicker">Economics</span><h3>Marketplace math</h3><div class="mixRows"><div class="mixRow"><span>Gross</span><div class="mixBar"><i style="width:100%"></i></div><strong>${money(dashboard.grossSales)}</strong></div><div class="mixRow"><span>YasReady fee</span><div class="mixBar"><i style="width:5%"></i></div><strong>${money(dashboard.marketplaceFees)}</strong></div><div class="mixRow"><span>Author</span><div class="mixBar"><i style="width:65%"></i></div><strong>${money(dashboard.authorEarnings)}</strong></div></div><p>Demo numbers only. Production accounting will store fulfillment cost, Stripe fee, tax, refund, marketplace fee and seller payable separately per order item.</p></section></div>
  <section class="panel" style="margin-top:14px"><span class="kicker">Recent orders</span><h3>Order + fulfillment ledger</h3><div class="orderRows">${dashboard.recentOrders.map(o=>`<div class="orderRow"><strong>${o.id}</strong><div><strong>${o.title}</strong><small>${o.when}</small></div><span>${o.format}<br><b>${money(o.gross)}</b></span><span class="statusTag ${o.status==='Delivered'?'good':''}">${o.status}</span></div>`).join('')}</div></section></div></main>`}
function marketingView(){const b=books[1];const defaultUrl=campaignUrl(b,'launch','author-kit');const embed=`<a href="${defaultUrl}" data-yasready-book="${b.slug}" style="display:inline-flex;align-items:center;gap:10px;padding:12px 16px;border-radius:12px;background:#1d1d1f;color:white;text-decoration:none;font:700 14px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif">Buy ${b.title} on YasReady →</a>`;return `<main class="view dashboard"><div class="shell"><div class="marketingHero"><span class="kicker">Included with Marketplace</span><h2>Sell the book everywhere.</h2><p>Every live title gets a free promotional toolkit. The important part: every asset can carry attribution so the author learns what actually drives visits and sales.</p></div><div class="kitGrid"><section class="toolCard"><span class="kicker">Smart campaign link</span><h3>One link, fully trackable.</h3><p>Create links for Instagram, email, events, your website, a podcast or anything else. Campaign IDs are stored as first-class attribution data.</p><div class="formRow"><input id="campaignName" class="field" value="launch" aria-label="Campaign name"><select id="campaignSource" class="field"><option value="instagram">Instagram</option><option value="email">Email</option><option value="website">Website</option><option value="event">Event</option><option value="podcast">Podcast</option></select></div><div class="linkResult"><input id="campaignLink" class="field" readonly value="${defaultUrl}"><button class="btn primary small" data-copy="#campaignLink">Copy</button></div><div class="miniStats"><div class="miniStat"><span>Visits</span><strong>109</strong></div><div class="miniStat"><span>Sales</span><strong>11</strong></div><div class="miniStat"><span>Conversion</span><strong>10.1%</strong></div></div></section>
  <section class="toolCard"><span class="kicker">QR code</span><h3>From real life to checkout.</h3><p>Use the exact same campaign URL on signing tables, bookmarks, launch parties, postcards or a back-of-book page.</p><div class="qrWrap"><div class="qrBox"><canvas id="qr"></canvas></div><div><strong>Event QR — ${b.title}</strong><p>This QR is generated locally in the browser. No external QR service receives the URL.</p><button class="btn secondary small" id="downloadQr">Download PNG</button></div></div></section>
  <section class="toolCard"><span class="kicker">Website embed</span><h3>A buy button authors can paste anywhere.</h3><p>Simple HTML keeps this usable on most websites while still preserving YasReady campaign attribution.</p><div id="embedCode" class="codeBox">${escapeHtml(embed)}</div><button class="btn secondary small" style="margin-top:10px" data-copy-text="${encodeURIComponent(embed)}">Copy HTML</button></section>
  <section class="toolCard"><span class="kicker">Ready-to-post copy</span><h3>Stop staring at a blank caption box.</h3><p>Free launch copy can be generated from metadata YasReady already knows. v0.1.0 ships a deterministic starter; AI generation can be connected later without changing the campaign model.</p><div class="codeBox" id="socialCopy">Fault Lines is officially available in paperback and ebook. If you’ve been waiting to continue Tres Amigos, Una Vida, this is your sign. Read it here: ${defaultUrl}</div><button class="btn secondary small" style="margin-top:10px" data-copy="#socialCopy">Copy post</button></section></div></div></main>`}
function escapeHtml(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function cartDrawer(){const subtotal=state.cart.reduce((a,x)=>a+x.price,0);return `<div class="cartDrawer" data-close-cart><aside class="cartPanel" onclick="event.stopPropagation()"><div class="drawerHead"><h2>Your cart</h2><button class="closeBtn" data-close-cart>×</button></div>${state.cart.length?`<div class="cartItems">${state.cart.map((x,i)=>`<div class="cartItem"><div><strong>${x.title}</strong><span>${x.format} · ${x.author}</span></div><div><strong>${money(x.price)}</strong><button class="removeBtn" data-remove="${i}">Remove</button></div></div>`).join('')}</div><div class="totals"><div class="totalRow"><span>Subtotal</span><span>${money(subtotal)}</span></div><div class="totalRow"><span>Shipping / tax</span><span>Calculated later</span></div><div class="totalRow big"><span>Total</span><span>${money(subtotal)}</span></div></div><div class="notice"><strong>Demo checkout is intentionally locked.</strong><br>The production endpoint requires server-side inventory/fulfillment validation, Stripe Checkout creation and webhook certification before CHECKOUT_ENABLED can be turned on.</div><button class="btn primary" style="width:100%;margin-top:12px" data-demo-checkout>Demo checkout flow</button>`:`<div class="empty"><strong>Your cart is empty.</strong><p>Add a live edition from any book.</p></div>`}</aside></div>`}
function bookModal(b){return `<div class="bookModal" data-close-book><article class="bookModalCard" onclick="event.stopPropagation()"><div class="drawerHead"><span></span><button class="closeBtn" data-close-book>×</button></div><div class="bookDetail">${cover(b)}<div><span class="kicker">${b.series?`${b.series}${b.seriesNumber?` · Book ${b.seriesNumber}`:''}`:'YasReady Marketplace'}</span><h1>${b.title}</h1><strong>${b.author}</strong><p class="lead">${b.longDescription}</p><div class="rating">★ ${b.rating} · ${b.reviews} reviews · ${b.categories.join(' · ')}</div><div class="editionList">${b.editions.map(e=>`<div class="editionRow ${e.status==='live'?'':'unavailable'}"><div><strong>${e.format}</strong><span>${e.status==='live'?(e.fulfillment==='ingram'?'Print fulfillment ready':'Digital delivery ready'):`Status: ${e.status}`}</span></div><strong class="price">${money(e.price)}</strong><button class="btn ${e.status==='live'?'primary':'secondary'} small" ${e.status==='live'?`data-add="${b.id}|${e.id}"`:'disabled'}>${e.status==='live'?'Add to cart':'Not live yet'}</button></div>`).join('')}</div></div></div></article></div>`}
function render(){app.innerHTML=shell()+({store:storeView,dashboard:dashboardView,marketing:marketingView}[state.view]())+`<footer class="shell"><button class="brand" data-nav="store">${brandMark}<span>Marketplace | YasReady</span></button><span>© 2026 OutAt Inc. Demo foundation.</span><span>marketplace.yasready.com</span></footer>`+(state.selected?bookModal(state.selected):'');bind();if(state.view==='marketing')setupMarketing()}
function toast(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.append(x);setTimeout(()=>x.remove(),2400)}
function bind(){
 document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>{state.view=x.dataset.nav;state.selected=null;track('navigation',{view:state.view});render();scrollTo(0,0)});
 document.querySelector('[data-cart]')?.addEventListener('click',()=>{document.body.insertAdjacentHTML('beforeend',cartDrawer());bindCart();track('cart_opened')});
 document.querySelectorAll('[data-book]').forEach(x=>x.onclick=()=>{state.selected=books.find(b=>b.id===x.dataset.book);track('book_viewed',{bookId:state.selected.id});render()});
 document.querySelectorAll('[data-close-book]').forEach(x=>x.onclick=()=>{state.selected=null;render()});
 document.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>{const [bid,eid]=x.dataset.add.split('|'),b=books.find(z=>z.id===bid),e=b.editions.find(z=>z.id===eid);state.cart.push({bookId:b.id,editionId:e.id,title:b.title,author:b.author,authorId:b.authorId,format:e.format,price:e.price,fulfillment:e.fulfillment});persistCart();track('cart_item_added',{bookId:b.id,editionId:e.id,format:e.format,price:e.price,authorId:b.authorId});toast(`${e.format} added to cart`);render()});
 document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{state.filter=x.dataset.filter;track('catalog_filtered',{filter:state.filter});render();document.querySelector('#browse')?.scrollIntoView()});
 const s=document.querySelector('#search'); if(s)s.oninput=e=>{state.query=e.target.value;clearTimeout(window.__q);window.__q=setTimeout(()=>{track('catalog_searched',{query:state.query});render();document.querySelector('#search')?.focus()},180)};
 document.querySelectorAll('[data-scroll]').forEach(x=>x.onclick=()=>document.querySelector('#'+x.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));
 document.querySelectorAll('[data-toast]').forEach(x=>x.onclick=()=>toast(x.dataset.toast));
}
function bindCart(){document.querySelectorAll('[data-close-cart]').forEach(x=>x.onclick=()=>document.querySelector('.cartDrawer')?.remove());document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{state.cart.splice(Number(x.dataset.remove),1);persistCart();document.querySelector('.cartDrawer')?.remove();render();document.body.insertAdjacentHTML('beforeend',cartDrawer());bindCart()});document.querySelector('[data-demo-checkout]')?.addEventListener('click',()=>{track('checkout_demo_started',{items:state.cart.length,gross:state.cart.reduce((a,x)=>a+x.price,0),sellerCount:new Set(state.cart.map(x=>x.authorId)).size});toast('Checkout plumbing is ready; live money stays locked in v0.1.0.')})}
async function setupMarketing(){const b=books[1],campaign=document.querySelector('#campaignName'),source=document.querySelector('#campaignSource'),link=document.querySelector('#campaignLink'),canvas=document.querySelector('#qr');async function update(){const url=campaignUrl(b,campaign.value||'campaign',source.value);link.value=url;await QRCode.toCanvas(canvas,url,{width:264,margin:1});track('marketing_asset_previewed',{type:'campaign_link',bookId:b.id,campaign:campaign.value,source:source.value})}campaign.oninput=update;source.onchange=update;await update();document.querySelectorAll('[data-copy]').forEach(x=>x.onclick=async()=>{const el=document.querySelector(x.dataset.copy);const txt='value'in el?el.value:el.textContent;await navigator.clipboard.writeText(txt);track('marketing_asset_copied',{type:'text_or_link',bookId:b.id});toast('Copied')});document.querySelectorAll('[data-copy-text]').forEach(x=>x.onclick=async()=>{await navigator.clipboard.writeText(decodeURIComponent(x.dataset.copyText));track('marketing_asset_copied',{type:'embed',bookId:b.id});toast('HTML copied')});document.querySelector('#downloadQr').onclick=()=>{const a=document.createElement('a');a.download=`${b.slug}-${campaign.value||'campaign'}-qr.png`;a.href=canvas.toDataURL('image/png');a.click();track('marketing_asset_downloaded',{type:'qr',bookId:b.id,campaign:campaign.value,source:source.value})}}

const params=new URLSearchParams(location.search);if(params.get('book')){const found=books.find(b=>b.slug===params.get('book'));if(found)state.selected=found;track('campaign_landing',{bookSlug:params.get('book'),utm_source:params.get('utm_source'),utm_campaign:params.get('utm_campaign'),yr_campaign:params.get('yr_campaign')})}
render();
