import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {INGRAM_OPERATIONS_SCHEMA,normalizeTitleMapping,normalizeCostRow,syncFreshness,invoiceVariance,normalizeDeadLetterAction,normalizeExternalSaleRow,ingramOperationsReadiness,summarizeIngramOperations} from '../src/lib/ingram-operations.mjs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');

test('v0.12 operations contract is versioned',()=>assert.equal(INGRAM_OPERATIONS_SCHEMA,'yasready.ingram.operations.v1'));
test('v0.12 title mapping requires edition and ISBN',()=>{assert.throws(()=>normalizeTitleMapping({isbn:'9781'}),/edition_id_required/);assert.throws(()=>normalizeTitleMapping({editionId:'e1'}),/isbn_required/);const m=normalizeTitleMapping({editionId:'e1',isbn:'978-1-23',providerSku:'SKU',status:'verified',unitCostMinor:525});assert.equal(m.isbn,'978123');assert.equal(m.status,'verified');assert.equal(m.unitCostMinor,525)});
test('v0.12 cost rows reject missing or negative cost',()=>{assert.throws(()=>normalizeCostRow({isbn:'9781'}),/unit_cost_required/);assert.throws(()=>normalizeCostRow({isbn:'9781',unitCostMinor:-1}),/unit_cost_required/);assert.equal(normalizeCostRow({isbn:'9781',unitCostMinor:499}).unitCostMinor,499)});
test('v0.12 sync freshness distinguishes fresh stale and missing',()=>{assert.equal(syncFreshness(null).status,'missing');assert.equal(syncFreshness('2026-09-21T00:00:00Z',{nowAt:'2026-09-22T00:00:00Z',maxAgeHours:48}).status,'fresh');assert.equal(syncFreshness('2026-09-01T00:00:00Z',{nowAt:'2026-09-22T00:00:00Z',maxAgeHours:48}).status,'stale')});
test('v0.12 invoice reconciliation has bounded tolerance',()=>{assert.equal(invoiceVariance({expectedMinor:1000,actualMinor:1000}).status,'exact');assert.equal(invoiceVariance({expectedMinor:1000,actualMinor:1040,toleranceMinor:50}).status,'within_tolerance');assert.equal(invoiceVariance({expectedMinor:1000,actualMinor:1200,toleranceMinor:50,toleranceBps:100}).status,'variance')});
test('v0.12 dead-letter actions require notes for terminal decisions',()=>{assert.deepEqual(normalizeDeadLetterAction({action:'retry'}),{action:'retry',note:null});assert.throws(()=>normalizeDeadLetterAction({action:'resolve'}),/resolution_note_required/);assert.equal(normalizeDeadLetterAction({action:'ignore',note:'Known provider duplicate'}).action,'ignore')});
test('v0.12 external sale normalization keeps provider sales separate',()=>{const x=normalizeExternalSaleRow({externalSaleId:'s1',saleDate:'2026-09-01',isbn:'978-1',quantity:2,netMinor:1400});assert.equal(x.isbn,'9781');assert.equal(x.quantity,2);assert.throws(()=>normalizeExternalSaleRow({saleDate:'x'}),/external_sale_id_required/)});
test('v0.12 readiness remains fail closed by default',()=>{const r=ingramOperationsReadiness({},{});assert.equal(r.status,'not_ready');assert.ok(r.checks.find(x=>x.code==='live_submission'&&!x.pass));assert.ok(r.checks.find(x=>x.code==='approved_transport'&&!x.pass))});
test('v0.12 readiness can become live-ready only with explicit transport and clean data',()=>{const cfg={INGRAM_MODE:'partner',INGRAM_ACCOUNT_ID:'acct',PROVIDER_IMPORT_SECRET:'secret',INGRAM_METADATA_IMPORT_ENABLED:'true',INGRAM_INVENTORY_IMPORT_ENABLED:'true',INGRAM_FULFILLMENT_IMPORT_ENABLED:'true',INGRAM_INVOICE_IMPORT_ENABLED:'true',INGRAM_SUBMISSION_ENABLED:'true',INGRAM_REPORT_IMPORT_ENABLED:'true'};const m={physicalEditions:4,mappedPhysicalEditions:4,staleMetadata:0,missingMetadata:0,staleInventory:0,missingInventory:0,openDeadLetters:0,openReconciliationCases:0};assert.equal(ingramOperationsReadiness(cfg,m).status,'live_ready')});
test('v0.12 operation summary keeps queue exceptions and external sales separate',()=>{const s=summarizeIngramOperations({jobs:[{status:'queued'},{status:'shipped'}],deadLetters:[{status:'open'}],mappings:[{mapping_status:'verified'}],reconciliationCases:[{status:'open'}],externalSales:[{quantity:2,net_minor:1000}]});assert.equal(s.jobs.queued,1);assert.equal(s.jobs.shipped,1);assert.equal(s.exceptions.open,1);assert.equal(s.externalSales.netMinor,1000)});
test('v0.12 migration adds mappings reconciliation readiness and repair history',()=>{const sql=read('../migrations/0014_ingram_operations.sql');for(const t of ['provider_title_mappings','provider_cost_refresh_runs','provider_reconciliation_cases','provider_dead_letter_events','provider_readiness_runs','provider_readiness_items'])assert.match(sql,new RegExp(t))});
test('v0.12 worker exposes author/admin operations and cost import APIs',()=>{const w=read('../src/worker.mjs');for(const x of ['/api/me/ingram/operations','/api/admin/ingram/operations','/api/admin/ingram/title-mappings','/api/admin/ingram/readiness/run','/api/providers/ingram/costs/import'])assert.ok(w.includes(x))});
test('v0.12 dangerous Ingram switches remain off',()=>{const w=read('../wrangler.jsonc');for(const x of ['"INGRAM_SUBMISSION_ENABLED": "false"','"INGRAM_INVOICE_IMPORT_ENABLED": "false"','"INGRAM_FULFILLMENT_IMPORT_ENABLED": "false"','"INGRAM_COST_IMPORT_ENABLED": "false"'])assert.ok(w.includes(x))});
